import { spawn } from 'node:child_process';
import { randomUUID } from 'node:crypto';
import { readFileSync } from 'node:fs';
import fs from 'node:fs/promises';
import path from 'node:path';
import type { CmaClient } from '@datocms/cli-utils';
import { generateSchemaTypes } from '@datocms/cma-schema-types-generator';
import envPaths from 'env-paths';
import ts from 'typescript';
import { withLock } from './locks';

interface GlobalSource {
  module: string;
  alias: string;
}

const GLOBAL_SOURCES: readonly GlobalSource[] = [
  { module: '@datocms/cma-client-node', alias: 'CmaClientNode' },
  { module: 'datocms-structured-text-utils', alias: 'StructuredTextUtils' },
  {
    module: 'datocms-structured-text-dastdown',
    alias: 'StructuredTextDastdown',
  },
];

const WORKSPACE_LOCK_NAME = 'script-workspace-init';
const RUNS_DIRNAME = 'runs';
const VERSION_FILENAME = '.cli-version';

export interface EnsureResult {
  rebuilt: boolean;
  installed: boolean;
}

export interface ValidationOutput {
  passed: boolean;
  output: string;
}

export type ExecutionResult =
  | { success: true }
  | { success: false; cause: 'exitCode'; exitCode: number }
  | { success: false; cause: 'timeout' }
  | { success: false; cause: 'error'; error: string };

export interface WorkspaceOptions {
  rebuild?: boolean;
}

/**
 * Manages the isolated workspace used to run one-off cma:script invocations.
 * The workspace lives in the user's platform data dir and owns its own
 * node_modules with @datocms/cma-client-node / tsx / typescript versions
 * synced from whatever the CLI currently resolves.
 *
 * Concurrent invocations are isolated via per-run subdirectories under
 * `runs/<uuid>/`: each contains its own `schema.ts`, `script.ts`, and
 * `tsconfig.json` so `tsc --noEmit` only sees that run's files. Heavy bits
 * (`node_modules`, `runner.ts`, `globals.d.ts`, `package.json`) stay shared
 * at the workspace root.
 */
export class ScriptWorkspace {
  readonly rootPath: string;
  readonly runsPath: string;

  constructor(rootPath?: string) {
    this.rootPath =
      rootPath ??
      path.join(
        envPaths('datocms-cli', { suffix: '' }).data,
        'script-workspace',
      );
    this.runsPath = path.join(this.rootPath, RUNS_DIRNAME);
  }

  async ensure(opts: WorkspaceOptions = {}): Promise<EnsureResult> {
    return withLock(
      WORKSPACE_LOCK_NAME,
      async () => {
        const cliVersion = this.getCliVersion();
        const versionFile = path.join(this.rootPath, VERSION_FILENAME);
        const recordedVersion = (await this.readFileSafe(versionFile))?.trim();
        const rootExists = await this.fileExists(this.rootPath);
        // Missing version file on a pre-existing root means a legacy (or
        // crashed) workspace from before version-tracking was introduced —
        // treat it as a mismatch so we wipe stale shape (e.g. legacy
        // `scripts/` dir, root `tsconfig.json`).
        const versionMismatch = rootExists && recordedVersion !== cliVersion;

        const shouldRebuild = opts.rebuild || versionMismatch;

        if (shouldRebuild) {
          await fs.rm(this.rootPath, { recursive: true, force: true });
        }

        await fs.mkdir(this.rootPath, { recursive: true });
        await fs.mkdir(this.runsPath, { recursive: true });

        const pkgChanged = await this.writePackageJson();
        await this.writeRunner();

        const nodeModulesExists = await this.fileExists(
          path.join(this.rootPath, 'node_modules'),
        );

        const needsInstall = shouldRebuild || pkgChanged || !nodeModulesExists;

        if (needsInstall) {
          await this.installDeps();
        }

        // globals.d.ts is generated by enumerating the installed packages,
        // so it must run after `npm install`. Regenerate whenever deps could
        // have changed (rebuild, install, or missing file).
        const globalsPath = path.join(this.rootPath, 'globals.d.ts');
        const globalsExists = await this.fileExists(globalsPath);
        if (shouldRebuild || needsInstall || !globalsExists) {
          await this.writeGlobalsDeclaration();
        }

        await fs.writeFile(versionFile, cliVersion, { encoding: 'utf8' });

        return { rebuilt: shouldRebuild, installed: needsInstall };
      },
      { timeoutMs: 5 * 60 * 1000 },
    );
  }

  async writeScriptAndSchema(
    client: CmaClient.Client,
    scriptContent: string,
    options: { generateSchema?: boolean } = {},
  ): Promise<{ runDir: string; scriptPath: string; schemaPath: string }> {
    const { generateSchema = true } = options;

    const runDir = path.join(this.runsPath, randomUUID());
    await fs.mkdir(runDir, { recursive: true });

    const schemaPath = path.join(runDir, 'schema.ts');
    const schemaTypes = generateSchema
      ? await generateSchemaTypes(client)
      : '// Schema types not generated (script does not reference `Schema.*`).\nexport {};\n';
    await fs.writeFile(schemaPath, schemaTypes, { encoding: 'utf8' });

    const scriptPath = path.join(runDir, 'script.ts');
    await fs.writeFile(scriptPath, scriptContent, { encoding: 'utf8' });

    await this.writeSchemaGlobals(runDir);
    await this.writeRunTsConfig(runDir);

    return { runDir, scriptPath, schemaPath };
  }

  private async writeSchemaGlobals(runDir: string): Promise<void> {
    const content = `import * as SchemaModule from './schema.js';

declare global {
  export import Schema = SchemaModule;
}

(globalThis as unknown as { Schema: typeof SchemaModule }).Schema =
  SchemaModule;
`;

    await fs.writeFile(path.join(runDir, 'schema-globals.ts'), content, {
      encoding: 'utf8',
    });
  }

  async cleanupRun(runDir: string): Promise<void> {
    await fs.rm(runDir, { recursive: true, force: true }).catch(() => {});
  }

  async validate(runDir: string): Promise<ValidationOutput> {
    return new Promise((resolve, reject) => {
      const tsc = spawn(
        'npx',
        ['tsc', '--noEmit', '-p', '.', '--pretty', 'false'],
        { cwd: runDir, env: process.env },
      );

      let stdout = '';
      let stderr = '';

      tsc.stdout?.on('data', (b) => {
        stdout += b.toString();
      });
      tsc.stderr?.on('data', (b) => {
        stderr += b.toString();
      });
      tsc.on('error', reject);
      tsc.on('close', (code) => {
        resolve({
          passed: (code ?? 1) === 0,
          output: `${stderr}${stdout}`.trim(),
        });
      });
    });
  }

  async execute(
    scriptPath: string,
    opts: {
      apiToken: string;
      environment?: string;
      baseUrl?: string;
      timeoutMs?: number;
    },
  ): Promise<ExecutionResult> {
    const runnerPath = path.join(this.rootPath, 'runner.ts');

    return new Promise<ExecutionResult>((resolve) => {
      const env: NodeJS.ProcessEnv = {
        ...process.env,
        DATOCMS_API_TOKEN: opts.apiToken,
      };
      if (opts.environment) env.DATOCMS_ENVIRONMENT = opts.environment;
      if (opts.baseUrl) env.DATOCMS_BASE_URL = opts.baseUrl;

      const child = spawn('npx', ['tsx', runnerPath, scriptPath], {
        cwd: this.rootPath,
        env,
        stdio: 'inherit',
      });

      let timedOut = false;
      const killTimer =
        typeof opts.timeoutMs === 'number' && opts.timeoutMs > 0
          ? setTimeout(() => {
              timedOut = true;
              child.kill('SIGKILL');
            }, opts.timeoutMs)
          : undefined;

      child.on('close', (code) => {
        if (killTimer) clearTimeout(killTimer);

        if (timedOut) {
          resolve({ success: false, cause: 'timeout' });
          return;
        }

        if (code && code !== 0) {
          resolve({ success: false, cause: 'exitCode', exitCode: code });
          return;
        }

        resolve({ success: true });
      });

      child.on('error', (error) => {
        if (killTimer) clearTimeout(killTimer);
        resolve({ success: false, cause: 'error', error: error.message });
      });
    });
  }

  private async installDeps(): Promise<void> {
    await new Promise<void>((resolve, reject) => {
      const child = spawn('npm', ['install', '--no-audit', '--no-fund'], {
        cwd: this.rootPath,
        env: process.env,
        stdio: ['ignore', 'pipe', 'pipe'],
      });
      let stderr = '';
      child.stderr?.on('data', (b) => {
        stderr += b.toString();
      });
      child.on('close', (code) => {
        if (code === 0) {
          resolve();
        } else {
          reject(
            new Error(
              `npm install failed in workspace (exit ${code}): ${stderr.trim()}`,
            ),
          );
        }
      });
      child.on('error', reject);
    });
  }

  private async writePackageJson(): Promise<boolean> {
    const cmaClientNodeVersion = this.resolveDepVersion(
      '@datocms/cma-client-node',
    );
    const tsxVersion = this.resolveDepVersion('tsx');
    const typescriptVersion = this.resolveDepVersion('typescript');

    const pkg = {
      name: 'datocms-cli-script-workspace',
      private: true,
      type: 'module',
      dependencies: {
        '@datocms/cma-client-node': `^${cmaClientNodeVersion}`,
        'datocms-structured-text-utils': '^5.1.7',
        'datocms-structured-text-dastdown': '^5.1.11',
      },
      devDependencies: {
        '@types/node': '^24.10.1',
        tsx: `^${tsxVersion}`,
        typescript: `^${typescriptVersion}`,
      },
    };

    const serialized = `${JSON.stringify(pkg, null, 2)}\n`;
    const pkgPath = path.join(this.rootPath, 'package.json');
    const existing = await this.readFileSafe(pkgPath);

    if (existing === serialized) {
      return false;
    }

    await fs.writeFile(pkgPath, serialized, { encoding: 'utf8' });
    return true;
  }

  private async writeRunTsConfig(runDir: string): Promise<void> {
    const tsConfig = {
      compilerOptions: {
        target: 'ES2020',
        module: 'nodenext',
        moduleResolution: 'nodenext',
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        resolveJsonModule: true,
        noEmit: true,
      },
      include: [
        './schema.ts',
        './schema-globals.ts',
        './script.ts',
        '../../globals.d.ts',
      ],
    };

    const serialized = `${JSON.stringify(tsConfig, null, 2)}\n`;
    await fs.writeFile(path.join(runDir, 'tsconfig.json'), serialized, {
      encoding: 'utf8',
    });
  }

  private getCliVersion(): string {
    const pkgPath = path.join(__dirname, '..', '..', '..', 'package.json');
    return JSON.parse(readFileSync(pkgPath, 'utf-8')).version;
  }

  private async writeRunner(): Promise<void> {
    const moduleImports = GLOBAL_SOURCES.map(
      (s) => `import * as ${s.alias} from '${s.module}';`,
    ).join('\n');
    const moduleAliases = GLOBAL_SOURCES.map((s) => s.alias).join(', ');

    const runner = `import { buildClient } from '@datocms/cma-client-node';
${moduleImports}
import path from 'node:path';
import { pathToFileURL } from 'node:url';

function exposeAsGlobals(mod: Record<string, unknown>) {
  const target = globalThis as Record<string, unknown>;
  for (const [key, value] of Object.entries(mod)) {
    if (key === 'default' || key === '__esModule') continue;
    target[key] = value;
  }
}

async function main() {
  const scriptPath = process.argv[2];
  const apiToken = process.env['DATOCMS_API_TOKEN'];
  const environment = process.env['DATOCMS_ENVIRONMENT'];
  const baseUrl = process.env['DATOCMS_BASE_URL'];

  if (!scriptPath) {
    console.error('Missing script path argument');
    process.exit(2);
  }

  if (!apiToken) {
    console.error('Missing DATOCMS_API_TOKEN environment variable');
    process.exit(2);
  }

  const client = buildClient({ apiToken, environment, baseUrl });

  // Expose client as ambient global for stdin-mode scripts.
  (globalThis as unknown as { client: typeof client }).client = client;

  // Spread every named export of the supported DatoCMS modules onto
  // globalThis so stdin-mode scripts don't need to import them. The matching
  // type-side declarations are auto-generated in globals.d.ts.
  for (const mod of [${moduleAliases}]) {
    exposeAsGlobals(mod as unknown as Record<string, unknown>);
  }

  // Wire up the runtime \`Schema\` global from the per-run schema-globals.ts.
  // The type-side global is declared inside that file via \`declare global\`.
  const runDir = path.dirname(scriptPath);
  await import(pathToFileURL(path.join(runDir, 'schema-globals.ts')).href);

  const scriptUrl = scriptPath.startsWith('file://')
    ? scriptPath
    : pathToFileURL(scriptPath).href;

  const mod = await import(scriptUrl);

  // Format A: default export async function — call it with client.
  // Format B: no default export — script already ran via top-level await.
  if (typeof mod?.default === 'function') {
    await mod.default(client);
  }
}

main().catch((err) => {
  console.error(err instanceof Error ? err.stack ?? err.message : err);
  process.exit(1);
});
`;

    const runnerPath = path.join(this.rootPath, 'runner.ts');
    const existing = await this.readFileSafe(runnerPath);
    if (existing === runner) return;
    await fs.writeFile(runnerPath, runner, { encoding: 'utf8' });
  }

  /**
   * Generates `globals.d.ts` by enumerating each supported module's exports
   * via the TypeScript compiler API. The runtime side spreads every named
   * export onto `globalThis`; this file gives those names types so stdin-mode
   * scripts type-check without explicit imports. Auto-generation means a
   * library upgrade that adds, renames, or removes exports is picked up at
   * the next workspace install — no hand-maintained list to drift.
   */
  private async writeGlobalsDeclaration(): Promise<void> {
    const importLines = [
      "import type { Client } from '@datocms/cma-client-node';",
    ];
    const declarations: string[] = ['const client: Client;'];

    for (const source of GLOBAL_SOURCES) {
      importLines.push(`import * as ${source.alias} from '${source.module}';`);
      const exports = this.enumerateModuleExports(source.module);

      declarations.push('');
      declarations.push(`// ---- ${source.module} ----`);

      for (const exp of exports) {
        switch (exp.kind) {
          case 'namespace':
          case 'type':
          case 'value+type':
            // `import = ` is the universal form: it preserves generic
            // signatures, namespace shape, and value+type duality (classes,
            // enums). Inside `declare global`, `export import` lifts the
            // alias into the global scope.
            declarations.push(
              `export import ${exp.name} = ${source.alias}.${exp.name};`,
            );
            break;
          case 'value':
            // Plain value-only exports (functions, consts) — `import = ` does
            // not work on them, so fall back to a typed const.
            declarations.push(
              `const ${exp.name}: typeof ${source.alias}.${exp.name};`,
            );
            break;
        }
      }
    }

    const body = declarations
      .map((line) => (line === '' ? '' : `  ${line}`))
      .join('\n');

    const content = `${importLines.join('\n')}

declare global {
${body}
}

export {};
`;

    const filePath = path.join(this.rootPath, 'globals.d.ts');
    const existing = await this.readFileSafe(filePath);
    if (existing === content) return;
    await fs.writeFile(filePath, content, { encoding: 'utf8' });
  }

  private enumerateModuleExports(moduleName: string): Array<{
    name: string;
    kind: 'value' | 'type' | 'value+type' | 'namespace';
  }> {
    const probeFileName = `__enumerate-${randomUUID()}.ts`;
    const probePath = path.join(this.rootPath, probeFileName);
    const probeContent = `import * as M from '${moduleName}';\nexport { M };\n`;

    const compilerOptions: ts.CompilerOptions = {
      target: ts.ScriptTarget.ES2020,
      module: ts.ModuleKind.NodeNext,
      moduleResolution: ts.ModuleResolutionKind.NodeNext,
      esModuleInterop: true,
      skipLibCheck: true,
      noEmit: true,
      strict: false,
      allowJs: false,
    };

    const host = ts.createCompilerHost(compilerOptions, true);
    const originalGetSourceFile = host.getSourceFile.bind(host);
    const originalReadFile = host.readFile.bind(host);
    const originalFileExists = host.fileExists.bind(host);

    host.getSourceFile = (fileName, languageVersion, onError, shouldCreate) => {
      if (path.resolve(fileName) === probePath) {
        return ts.createSourceFile(
          fileName,
          probeContent,
          languageVersion,
          true,
        );
      }
      return originalGetSourceFile(
        fileName,
        languageVersion,
        onError,
        shouldCreate,
      );
    };
    host.readFile = (fileName) => {
      if (path.resolve(fileName) === probePath) return probeContent;
      return originalReadFile(fileName);
    };
    host.fileExists = (fileName) => {
      if (path.resolve(fileName) === probePath) return true;
      return originalFileExists(fileName);
    };
    host.getCurrentDirectory = () => this.rootPath;

    const program = ts.createProgram({
      rootNames: [probePath],
      options: compilerOptions,
      host,
    });

    const sourceFile = program.getSourceFile(probePath);
    if (!sourceFile) {
      throw new Error(
        `Could not load probe file while enumerating exports of "${moduleName}"`,
      );
    }

    const checker = program.getTypeChecker();
    const fileSymbol = checker.getSymbolAtLocation(sourceFile);
    if (!fileSymbol) {
      throw new Error(
        `Could not get symbol for probe file while enumerating exports of "${moduleName}"`,
      );
    }

    const fileExports = checker.getExportsOfModule(fileSymbol);
    const moduleAlias = fileExports.find((s) => s.getName() === 'M');
    if (!moduleAlias) {
      throw new Error(
        `Could not find module alias while enumerating exports of "${moduleName}"`,
      );
    }

    const moduleSymbol =
      moduleAlias.flags & ts.SymbolFlags.Alias
        ? checker.getAliasedSymbol(moduleAlias)
        : moduleAlias;

    const moduleExports = checker.getExportsOfModule(moduleSymbol);

    type ExportInfo = {
      name: string;
      kind: 'value' | 'type' | 'value+type' | 'namespace';
    };
    const result: ExportInfo[] = [];

    for (const exp of moduleExports) {
      const name = exp.getName();
      if (name === 'default' || name.startsWith('__')) continue;
      if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)) continue;

      let resolved = exp;
      // Walk through alias chains to the original symbol — that's where the
      // real flags (Function, Class, Module, ...) live.
      const seen = new Set<ts.Symbol>();
      while (resolved.flags & ts.SymbolFlags.Alias && !seen.has(resolved)) {
        seen.add(resolved);
        const next = checker.getAliasedSymbol(resolved);
        if (next === resolved) break;
        resolved = next;
      }

      const flags = resolved.flags;
      const isNamespace = !!(flags & ts.SymbolFlags.Module);
      const isValue = !!(flags & ts.SymbolFlags.Value);
      const isType = !!(flags & ts.SymbolFlags.Type);

      let kind: ExportInfo['kind'];
      if (isNamespace) {
        kind = 'namespace';
      } else if (isValue && isType) {
        kind = 'value+type';
      } else if (isValue) {
        kind = 'value';
      } else if (isType) {
        kind = 'type';
      } else {
        continue;
      }

      result.push({ name, kind });
    }

    result.sort((a, b) => a.name.localeCompare(b.name));
    return result;
  }

  private resolveDepVersion(pkg: string): string {
    try {
      const pkgJsonPath = require.resolve(`${pkg}/package.json`);
      const version: string = JSON.parse(
        readFileSync(pkgJsonPath, 'utf-8'),
      ).version;
      return version;
    } catch {
      throw new Error(
        `Could not resolve ${pkg}/package.json — is it installed as a dependency of datocms?`,
      );
    }
  }

  private async readFileSafe(filePath: string): Promise<string | null> {
    try {
      return await fs.readFile(filePath, 'utf-8');
    } catch {
      return null;
    }
  }

  private async fileExists(filePath: string): Promise<boolean> {
    try {
      await fs.stat(filePath);
      return true;
    } catch {
      return false;
    }
  }
}
